# Generated by Django 2.0.7 on 2019-04-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=255)),
                ('event_start', models.DateTimeField(null=True)),
                ('event_code', models.CharField(blank=True, max_length=255)),
                ('event_url', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
