# Generated by Django 2.2 on 2019-09-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190429_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='api_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
