# Generated by Django 2.2 on 2019-10-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
