# Generated by Django 2.0.7 on 2019-01-11 10:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='organiser_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='organiser_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='organiser_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='newspage',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='name'),
        ),
    ]
