# Generated by Django 2.0.7 on 2019-01-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190111_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='display_until',
        ),
    ]
