# Generated by Django 2.0.7 on 2019-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newspage_display_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='publish_to_twitter',
            field=models.BooleanField(default=False, verbose_name='Check box to publish to Twitter'),
        ),
    ]
