# Generated by Django 2.0.7 on 2019-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newspage_publish_to_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='publish_to_twitter',
            field=models.BooleanField(default=False, verbose_name='Publish to Twitter?'),
        ),
    ]
