# Generated by Django 2.2 on 2019-09-14 16:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsindexpage_thanks_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
