# Generated by Django 2.2 on 2019-09-25 17:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190914_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='summary'),
        ),
    ]
