# Generated by Django 2.0.7 on 2018-10-17 14:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(max_length=250)),
                ('details', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='title')), ('summary', wagtail.core.blocks.RichTextBlock()), ('link', wagtail.core.blocks.URLBlock()), ('start_date', wagtail.core.blocks.DateTimeBlock(classname='start_date')), ('end_date', wagtail.core.blocks.DateTimeBlock(classname='end_date')), ('date', wagtail.core.blocks.DateBlock(classname='date')), ('date_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.DateBlock(label='course_date'))), ('document', wagtail.documents.blocks.DocumentChooserBlock(classname='documents')), ('name', wagtail.core.blocks.CharBlock(classname='name')), ('email', wagtail.core.blocks.EmailBlock()), ('number', wagtail.core.blocks.CharBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
