# Generated by Django 2.0.7 on 2018-10-21 14:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='date_list',
            field=wagtail.core.fields.StreamField([('date_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.DateBlock(group='course_dates')))]),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='end_date',
            field=wagtail.core.fields.StreamField([('end_date', wagtail.core.blocks.DateTimeBlock(group='course_dates'))]),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='start_date',
            field=wagtail.core.fields.StreamField([('start_date', wagtail.core.blocks.DateTimeBlock(group='course_dates'))]),
        ),
    ]
