# Generated by Django 2.0.7 on 2018-10-21 14:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20181021_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='date_list',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='dates',
            field=wagtail.core.fields.StreamField([('date_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.DateBlock(required=False)))], blank=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='end_date',
            field=wagtail.core.fields.StreamField([('end_date', wagtail.core.blocks.DateTimeBlock(required=False))], blank=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='start_date',
            field=wagtail.core.fields.StreamField([('start_date', wagtail.core.blocks.DateTimeBlock(required=False))], blank=True),
        ),
    ]
