# Generated by Django 2.0.7 on 2019-01-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_coursepage_latlng_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseindexpage',
            options={'verbose_name': 'Courses & Conferences Index Page'},
        ),
        migrations.AlterModelOptions(
            name='coursepage',
            options={'verbose_name': 'Courses & Conferences Page'},
        ),
    ]
