# Generated by Django 2.0.7 on 2018-10-21 15:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20181021_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='dates',
            field=wagtail.core.fields.StreamField([('date_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.DateBlock())), ('theme', wagtail.core.blocks.CharBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='summary',
            field=wagtail.core.fields.RichTextField(max_length=250),
        ),
    ]
