# Generated by Django 2.0.7 on 2018-10-21 15:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20181021_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='start_date',
            field=wagtail.core.fields.StreamField([('start_date', wagtail.core.blocks.DateTimeBlock(label='use this', required=False))], blank=True),
        ),
    ]
