# Generated by Django 2.0.7 on 2018-10-21 15:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20181021_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='end_date',
            field=wagtail.core.fields.StreamField([('end_date', wagtail.core.blocks.DateTimeBlock(label='', required=False))], blank=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='start_date',
            field=wagtail.core.fields.StreamField([('start_date', wagtail.core.blocks.DateTimeBlock(label='', required=False))], blank=True),
        ),
    ]
