# Generated by Django 2.0.7 on 2018-10-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20181021_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='end_date',
            field=models.DateTimeField(verbose_name='course end'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='start_date',
            field=models.DateTimeField(verbose_name='course start'),
        ),
    ]
