# Generated by Django 2.0.7 on 2018-10-21 16:24

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20181021_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='intro',
            field=models.CharField(max_length=250, verbose_name='one line summary'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='summary',
            field=wagtail.core.fields.RichTextField(max_length=250, verbose_name='full summary'),
        ),
    ]
