# Generated by Django 2.0.7 on 2018-10-21 19:12

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20181021_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='contact_details',
            field=wagtail.core.fields.StreamField([('name', wagtail.core.blocks.CharBlock(icon='user')), ('email', wagtail.core.blocks.EmailBlock()), ('number', wagtail.core.blocks.CharBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='dates',
            field=wagtail.core.fields.StreamField([('date_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock()), ('description', wagtail.core.blocks.CharBlock())])))], blank=True, help_text='if the course has several dates use this field'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='if the course has a start and end date use this field'),
        ),
    ]
