# Generated by Django 2.0.7 on 2018-10-21 19:21

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20181021_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='dates',
            field=wagtail.core.fields.StreamField([('date_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock()), ('description', wagtail.core.blocks.CharBlock())])))], blank=True, help_text='for courses with non consecutive dates'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='for courses with consecutive dates'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='summary',
            field=wagtail.core.fields.RichTextField(verbose_name='full summary'),
        ),
    ]
