# Generated by Django 2.0.7 on 2018-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_auto_20181022_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='end_date',
            field=models.DateTimeField(help_text='for courses with consecutive dates', null=True),
        ),
    ]
