# Generated by Django 2.0.7 on 2018-10-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_coursepagerelateddates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='start_date',
        ),
    ]
