# Generated by Django 2.0.7 on 2018-11-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_remove_coursepage_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='end_date',
        ),
    ]
