# Generated by Django 2.2 on 2019-11-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_auto_20191029_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('talk_0', models.CharField(max_length=128)),
                ('talk_1', models.CharField(max_length=128)),
                ('talk_2', models.CharField(max_length=128)),
                ('talk_3', models.CharField(max_length=128)),
                ('talk_4', models.CharField(max_length=128)),
                ('talk_5', models.CharField(max_length=128)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
