# Generated by Django 2.2 on 2019-11-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='useful_0',
            field=models.CharField(choices=[('NA', 'N/A'), ('SA', 'STRONGLY AGREE'), ('AA', 'AGREE'), ('NN', 'NEUTRAL'), ('DD', 'DISAGREE'), ('SD', 'STRONGLY DISAGREE')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='feedback',
            name='useful_1',
            field=models.CharField(choices=[('NA', 'N/A'), ('SA', 'STRONGLY AGREE'), ('AA', 'AGREE'), ('NN', 'NEUTRAL'), ('DD', 'DISAGREE'), ('SD', 'STRONGLY DISAGREE')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='feedback',
            name='useful_2',
            field=models.CharField(choices=[('NA', 'N/A'), ('SA', 'STRONGLY AGREE'), ('AA', 'AGREE'), ('NN', 'NEUTRAL'), ('DD', 'DISAGREE'), ('SD', 'STRONGLY DISAGREE')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='feedback',
            name='useful_3',
            field=models.CharField(choices=[('NA', 'N/A'), ('SA', 'STRONGLY AGREE'), ('AA', 'AGREE'), ('NN', 'NEUTRAL'), ('DD', 'DISAGREE'), ('SD', 'STRONGLY DISAGREE')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='feedback',
            name='useful_4',
            field=models.CharField(choices=[('NA', 'N/A'), ('SA', 'STRONGLY AGREE'), ('AA', 'AGREE'), ('NN', 'NEUTRAL'), ('DD', 'DISAGREE'), ('SD', 'STRONGLY DISAGREE')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='feedback',
            name='useful_5',
            field=models.CharField(choices=[('NA', 'N/A'), ('SA', 'STRONGLY AGREE'), ('AA', 'AGREE'), ('NN', 'NEUTRAL'), ('DD', 'DISAGREE'), ('SD', 'STRONGLY DISAGREE')], default='NA', max_length=2),
        ),
    ]
