# Generated by Django 2.2 on 2019-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20191112_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='talk_0',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='talk_1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='talk_2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='talk_3',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='talk_4',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='talk_5',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
