# Generated by Django 2.2 on 2019-11-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_auto_20191029_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.CharField(blank=True, max_length=255)),
                ('attended', models.BooleanField(blank=True, max_length=255)),
                ('feedback_complete', models.BooleanField(blank=True, max_length=255)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
