# Generated by Django 2.0.7 on 2018-12-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0002_blogpage_standardpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
