# Generated by Django 2.0.7 on 2018-09-09 11:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0004_eventpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventbritePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('event_description', wagtail.core.fields.RichTextField(blank=True)),
                ('event_start', models.DateTimeField(verbose_name='event start')),
                ('event_end', models.DateTimeField(verbose_name='event end')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
