# Generated by Django 2.1 on 2019-03-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
