# Generated by Django 2.1 on 2019-04-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190303_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='event',
        ),
    ]
