# Generated by Django 2.0.7 on 2019-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190120_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
