# Generated by Django 2.0.7 on 2019-01-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_event_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(null=True),
        ),
    ]
