# Generated by Django 2.0.7 on 2019-01-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyspage',
            old_name='url',
            new_name='survey_url',
        ),
    ]
