# Generated by Django 2.0.7 on 2019-01-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190111_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyspage',
            name='display_until',
        ),
    ]
